#!/bin/sh

# Setting volume name for taking snapshot. This volume is mounted in directory 'models'.
# Please replace "test_volume" as per your mount point.
volume_name="test_volume"

# Setting vserver
# Please replace it as per your vserver name
vserver="test-v-server"

# Setting user and host
# Please replace it as per your
snap_user_host="test-user@test-host"

# Creating snapshot for model versioning
echo "creating snapshot..."
snapshotid=$(git log --format="%H" -n 1)
ssh $snap_user_host snapshot create -vserver $vserver -volume $volume_name -snapshot $snapshotid
echo "snapshot with id $snapshotid is created"

# Link the created snapshot as the model version at this point of time

# If there is already an old versioned model directory, remove it 
if [ -d "./models.version" ] 
then
    rm -rf ./models.version 
fi

echo "Linking latest model version"
# Link the latest versioned model snapshot to the project directory. In our case, data.version includes latest snapshot
ln -s /mnt/.snapshot/"$snapshotid" ./models.version
