#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

# Creating snapshot for model versioning
echo "creating snapshot..."
snapshotid=$(git log --format="%H" -n 1)
ssh admin@trinidad snapshot create -vserver sguhr-trident-test -volume kubeflow_raw_data -snapshot $snapshotid
echo "snapshot with id $snapshotid is created"

# Link the created snapshot as the model version at this point of time

# If there is already an old versioned model directory, remove it 
if [ -d "./model.version" ] 
then
    rm -rf ./model.version 
fi

echo "Linking latest model version"
# Link the latest versioned model snapshot to the project directory. In our case, data.version includes latest snapshot
ln -s /mnt/.snapshot/"$snapshotid" ./model.version
